### PR TITLE
REPLACE action for replaceReducers

### LINKED ISSUE #1636: Redux.replaceReducer throw warning "Unexpected key found"
This issue was moved from https://github.com/reactjs/react-redux/issues/360

> Hello,
> I tried to do a code splitting on route change.
> 
> When the route changes to '/register', i dynamically add "registration" as one of the root state using replaceReducer and it work just fine.
> Once the registration completed i want to remove the reducer using replaceReducer again, but instead it return the following warning :
> 
> Unexpected key "registration" found in initialState argument passed to createStore. Expected to find one of the known reducer keys instead: ... Unexpected keys will be ignored.
> 
> Thanks in advance

### PR DESCRIPTION
**Pull request by timdorr**
Fixes #1636 

Provides a separate private action for when we replace reducers. This allows us to specifically handle this case, which resolves a false dev-only warning for combineReducers currently.

### CODE REVIEW

**Comment by quinnnned** [comment]
Hey that test looks familiar. 😉 Glad you liked it.

**Comment by quinnnned** [comment]
@timdorr what if the nextReducer depends on the INIT action for proper behavior?  Or is it just understood that a reducer must not depend on the INIT action?

**Comment by timdorr** [comment]
> Hey that test looks familiar. 😉 Glad you liked it. 

Yes, thank you! I'll amend the commit so you get credit.

**Comment by quinnnned** [comment]
Gotcha.  I also just saw Dan's advice in #186.  Should have done a quick google first.

**Comment by timdorr** [comment]
As requested in https://github.com/reactjs/redux/issues/1736#issuecomment-219484915, this also adds a randomized name to the private actions, making them harder to look for.

File: src/utils/actionTypes.js [hunk 1]
```diff
@@ -4,8 +4,9 @@
  * If the current state is undefined, you must return the initial state.
  * Do not reference these action types directly in your code.
  */
-var ActionTypes = {
-  INIT: '@@redux/INIT'
+const ActionTypes = {
+  INIT: '@@redux/INIT' + Math.random().toString(36).substring(7).split('').join('.'),
+  REPLACE: '@@redux/REPLACE' + Math.random().toString(36).substring(7).split('').join('.')
```
Comment (asantos00) [inline src/utils/actionTypes.js]: Does it makes sense to have this *random token generator* in a function ? (since it being used at least twice here)

Comment (timdorr) [reply src/utils/actionTypes.js]: Probably, if we start having more than just two. I'm find with the duplication for now.

Comment (lvivski) [reply src/utils/actionTypes.js]: Why do you need two separate random strings generated? Seems that you can generate it once and use in both action types.

Comment (timdorr) [reply src/utils/actionTypes.js]: Yes, but that seems like splitting hairs. It doesn't really matter.

Comment (lvivski) [reply src/utils/actionTypes.js]: Ok, fair enough. There's also https://github.com/reactjs/redux/blob/master/src/combineReducers.js#L72. Does it make any sense to put all of them in the same place?

Comment (quinnnned) [reply src/utils/actionTypes.js]: I'm with @timdorr here.  When applying the D.R.Y. principle, it is critical to distinguish between essential duplication and coincidental duplication, because trying to "DRY-up" the latter kind can increase code complexity.  In cases where it is not clear what kind of duplication it is, one best practice is to permit the duplication until it causes actual pain.  This seems to be what @timdorr is doing.

Comment (markerikson) [reply src/utils/actionTypes.js]: @quinned : highly relevant here: https://twitter.com/acemarke/status/901329101088215044 :)

**Comment by timdorr** [comment]
Without further objections, I think this is OK to merge in. If anyone has any issues with it, feel free to revert or submit a PR with improvements.
