### PR TITLE
Only warn for unexpected key once per key

### LINKED ISSUE #1748: combineReducers does not remove unexpected keys when reducers have no changes
For example in the following, I would expect `newState` to equal `{ id: 1234, name: 'hello' }` but it instead returns `currentState`.
```javascript
const currentState = { id: 1234, name: 'hello', unexpected: 4567 };
const reducer = combineReducers( { id, name } );
const newState = reducer( currentState, {} );
```

The additional key is harmless in code, but it is annoying since an error warning may be printed to console repeatedly. This case is pretty easy to run into if the redux tree is persisted and the data shape changes.

### PR DESCRIPTION
**Pull request by Aweary**
Resolves #1748 

Pretty simple, just keeps a caches and filters keys that have already been warned about.

I had to update one of the related tests as it expected some keys to be warned about multiple times.

### CODE REVIEW

File: src/combineReducers.js [hunk 1]
```diff
@@ -34,7 +36,9 @@ function getUnexpectedStateShapeWarningMessage(inputState, reducers, action) {
     )
   }
 
-  var unexpectedKeys = Object.keys(inputState).filter(key => !reducers.hasOwnProperty(key))
+  var unexpectedKeys = Object.keys(inputState).filter(key => !reducers.hasOwnProperty(key) && !unexpectedKeyCache[key])
```
Comment (gaearon) [inline src/combineReducers.js]: Let’s split this into several lines so they format more nicely?

File: src/combineReducers.js [hunk 2]
```diff
@@ -34,7 +36,9 @@ function getUnexpectedStateShapeWarningMessage(inputState, reducers, action) {
...
+
+  unexpectedKeys.forEach(key => unexpectedKeyCache[key] = true)
```
Comment (gaearon) [inline src/combineReducers.js]: Let’s use curly braces to make it clear it’s a side effect.

**Comment by gaearon** [comment]
Looks good to me after fixing the nits.

**Comment by Aweary** [comment]
@gaearon the nits have been fixed 👍

File: src/combineReducers.js [hunk 3]
```diff
@@ -2,6 +2,8 @@ import { ActionTypes } from './createStore'
 import isPlainObject from 'lodash/isPlainObject'
 import warning from './utils/warning'
 
+const unexpectedKeyCache = {}
```
Comment (gaearon) [inline src/combineReducers.js]: Let’s use `var` for consistency (we’ll codemod ’em all over later)

File: src/combineReducers.js [hunk 4]
```diff
@@ -34,7 +36,12 @@ function getUnexpectedStateShapeWarningMessage(inputState, reducers, action) {
     )
   }
 
-  var unexpectedKeys = Object.keys(inputState).filter(key => !reducers.hasOwnProperty(key))
+  var unexpectedKeys = Object.keys(inputState).filter(key =>
+  !reducers.hasOwnProperty(key) && !unexpectedKeyCache[key])
```
Comment (gaearon) [inline src/combineReducers.js]: I meant something like

```js
var unexpectedKeys = Object.keys(inputState).filter(key =>
  !reducers.hasOwnProperty(key) &&
  !unexpectedKeyCache[key]
)
```

**Comment by Aweary** [comment]
@gaearon changes made 👍

File: test/combineReducers.spec.js [hunk 5]
```diff
@@ -237,5 +237,26 @@ describe('Utils', () => {
 
       spy.restore()
     })
+
+    it('only warns for unexpected keys once', () => {
```
Comment (gaearon) [inline test/combineReducers.spec.js]: Do I undestand correctly that tests now depend on global shared state and run order? This doesn’t look very good.

File: src/combineReducers.js [hunk 6]
```diff
@@ -2,6 +2,8 @@ import { ActionTypes } from './createStore'
 import isPlainObject from 'lodash/isPlainObject'
 import warning from './utils/warning'
 
+var unexpectedKeyCache = {}
```
Comment (gaearon) [inline src/combineReducers.js]: Can/should we keep a cache per `combineReducers()` call?

Comment (Aweary) [inline src/combineReducers.js]: Yes, we definitely should, good call.

File: test/combineReducers.spec.js (hunk 5 above)
Comment (Aweary) [inline test/combineReducers.spec.js]: Right, that should be resolved by using individual cache instances per `combineReducers` call

File: src/combineReducers.js (hunk 6 above)
Comment (Aweary) [inline src/combineReducers.js]: I guess we could just create the cache within `combineReducers` and pass that to `getUnexpectedStateShapeWarningMessage`. Does that work for you @gaearon?

Comment (gaearon) [inline src/combineReducers.js]: Yea

File: test/combineReducers.spec.js (hunk 5 above)
Comment (gaearon) [inline test/combineReducers.spec.js]: Yep

**Comment by Aweary** [comment]
@gaearon I updated the PR so that it creates and passes a new cache to `getUnexpectedStateShapeWarningMessage` whenever `combineReducers` is called. I didn't see any existing code that indicated how you'd want to format these functions now that the argument list is rather long, so let me know if any changes are required 👍

File: src/combineReducers.js [hunk 7]
```diff
@@ -101,6 +99,7 @@ function assertReducerSanity(reducers) {
  */
 export default function combineReducers(reducers) {
   var reducerKeys = Object.keys(reducers)
+  var unexpectedKeyCache = {}
```
Comment (gaearon) [inline src/combineReducers.js]: Probably no need to declare it unless we’re in DEV.

File: src/combineReducers.js [hunk 8]
```diff
@@ -137,7 +136,7 @@ export default function combineReducers(reducers) {
       var previousStateForKey = state[key]
       var nextStateForKey = reducer(previousStateForKey, action)
       if (typeof nextStateForKey === 'undefined') {
-        var errorMessage = getUndefinedStateErrorMessage(key, action)
+        var errorMessage = getUndefinedStateErrorMessage(key, action, unexpectedKeyCache)
```
Comment (gaearon) [inline src/combineReducers.js]: I don’t think `getUndefinedStateErrorMessage` uses this?

Comment (Aweary) [inline src/combineReducers.js]: Sorry that was accidental

**Comment by Aweary** [comment]
@gaearon updated again. Fourth try's the charm.

**Comment by gaearon** [comment]
Have you tested this on a real project to check that it behaves as expected?

**Comment by Aweary** [comment]
I don't typically use the master branch of a library in real projects, I can run it on some of the example projects and verify the results if you like.

**Comment by Aweary** [comment]
@gaearon 

I tested the real-world example branch and verified it's working as expected. I changed the `rootReducer` call so it passed an invalid `foobar` value to the `pagination` reducer

```js
const rootReducer = combineReducers({
  entities,
  pagination: (state, action) => {
    return pagination(
      Object.assign({}, state, {foobar: false}),
      action
    )
  },
  errorMessage,
  routing
})
```

With the current release of redux this caused multiple warnings. After running `npm run build` and replacing the `lib` folder in the example project's `node_modules/redux` folder the error was only logged once no matter what actions were performed.

**Comment by gaearon** [comment]
👍
